mysite/mysite/urls.py
from django.contrib import admin
from  django.urls import include,path
#The include() function allows referencing other URLconfs

urlpatterns = [
    
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

mysite/polls/urls.py
from  django.urls import path

from  . import   views

app_name = 'polls'
urlpatterns = [
    # #ex: /polls/
    # path("", views.index, name="index"),
    # #ex /polls/5/
    # path("<int:question_id>/", views.detail, name="detail"),
    # #ex: /polls/5/results/
    # path("<int:question_id>/results/", views.results, name="results"),
    # #ex: /polls/5/vote/
    # path("<int:question_id>/vote/", views.vote, name="vote"),
    
    #updating view in django
    
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote.as_view(), name="vote"),
    
]

mysite/polls/models.py
from django.db import models
#importing models from django to be used in our enviroments
import datetime
from django.utils import timezone


class Question(models.Model):
    def __str__(self):
        return self.question_text
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    def was_published_recently(self):
     now = timezone.now()
     return now - datetime.timedelta(days=1) <= self.pub_date <= now
    




class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  
    # this code creates a relationship where
    # each instance of the current model is associated with a single Question instance
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    #this line of code defines an integer field
    # named "votes" in the current Django model.
    
    
    
    
    
    

mysite/polls/views.py
from typing import Any
from django.db import models
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
# from  django.shortcuts import Http404
from .models  import Choice,Question
from  django.http import  HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone


class  IndexView(generic.ListView):
    template_name  = "polls/index.html"
    context_object_name  =  "latest_question_list"
    
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :5
        ]
 
 



class  DetailView(generic.DetailView):
    # model =  Question
    # template_name  = "polls/detail.html"
     
    def  get_queryset(self):
        """
        Excludes any  questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())
        

class  ResultsView(generic.DetailView):
    model = Question
    template_name  =  "polls/detail.html"
   
   

class  vote(generic.DetailView):
    model  =  Question
    template_name  = "polls/results.html"
       

mysite/polls/templates/polls/detail.html
<form  action="{% url 'polls:vote'  question.id   %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{question.question_text}}</h1></legend>
        {% if error_message %}<p><strong></strong></p> {% endif%}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {%  endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Voting Index</title>
    
    <link rel="stylesheet" href="{% static "polls/style.css" %}">
</head>
<body>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        {% comment %} <li>{{question.id}}</li> {% endcomment %}
       <li><a href="{% url  'polls:detail'   question.id %}">{{question.question_text}}</a></li>
         
        {% endfor %}
    </ul>
{% else %}
<p>
    No polls are available.
</p>
{% endif %}
</body>
</html>

mysite/polls/templates/polls/results.html
<h1>{{question.question_text}}</h1>
<ul>
{% for choice  in question.choice_set.all %}
   <li>{{ choice.choice_text }} -- {{choice.votes}}
     vote{{choice.votes|pluralize}}
     {% endfor %}
   </li>
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>